version: "3.8"
services:
  db:
    image: mongo:7
    ports: [ "27017:27017" ]
  redis:
    image: redis:7-alpine
    ports: [ "6379:6379" ]
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports: [ "9200:9200" ]
